version: "3.8"

services:
  tcpcoupler:
    build: ./tcpCoupler
    ports:
      - "3001:3001"

  httpserver:
    build: ./httpServer
    ports:
      - "3002:3002"

  # ftpserver:
  #   image: delfer/alpine-ftp-server
  #   container_name: ftp-server
  #   ports:
  #     - "21:21" # FTP port
  #     - "21000-21010:21000-21010" # Passive FTP ports
  #   environment:
  #     - USERS="user|user" # FTP user and password
  #     - ADDRESS="0.0.0.0" # Listen on all interfaces
  #     # - FTP_USER=user
  #     # - FTP_PASS=user
  #     # - FTP_PORT=21
  #     # - FTP_BANNER=Welcome to FTP Server
  #   volumes:
  #     - ./etc:/etc/ # Mount the local 'etc' folder to '/etc' in the container

  # alpine-ftp-server:
  #   image: delfer/alpine-ftp-server
  #   ports:
  #     - "21:21"
  #     - 21000-21010:21000-21010
  #   environment:
  #     - USERS="one|1234"
  #     - ADDRESS=0.0.0.0
  #   volumes:
  #     - ./etc:/etc/